image: archlinux
packages:
  - git
  - libpulse
  - alsa-lib
  - python
  - python-pip
  - python-regex
  - python-wheel
  - rsync
  - swig
sources:
  - git@git.sr.ht:~jmr/vaxline
secrets:
  - 54baa0e1-63b8-4658-998d-941f7108ed84
environment:
  sshdest: >-
    srhtdeploy@cloud.steamboatfamilydoc.com
tasks:
  - install-pip-packages: |
      cd vaxline
      python3 -m pip install --user -r requirements.txt
  - run-agitester: |
      vaxline/agitester.py vaxline/vaxline.py
  - deploy-to-unicorn: |
      rsync -avz vaxline/ $sshdest:vaxline
      ssh $sshdest sudo python3 -m pip install -r vaxline/requirements.txt
      ssh $sshdest sudo rsync -avz vaxline/ /var/vaxline
